### ISSUE TITLE
测试自动提交脚本

### ISSUE THREAD

**Issue by wjlin0** [wjlin0/sccl_poc#1]
```yaml
id: halo-detect

info:
  name: halo detect
  author: wjlin0
  severity: info
  description: halo detect
  reference:
    - https://www.wjlin0.com
  tags: halo,java
http:
  - raw:
      - |+
        GET / HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
        Connection: close

    matchers:
      - type: regex
        part: body
        regex:
          - content="Halo [\d\.]+"
    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - content="Halo ([\d\.]+)"

```
https://www.wjlin0.com
